arm_link_1_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_joint_1
  gains:
    arm_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arm_link_2_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_joint_2
  gains:
    arm_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arm_link_3_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_joint_3
  gains:
    arm_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arm_link_4_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_joint_4
  gains:
    arm_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arm_link_5_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_joint_5
  gains:
    arm_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1