controller_list:
  - name: fake_arm_link_1_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_joint_1
  - name: fake_arm_link_2_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_joint_2
  - name: fake_arm_link_3_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_joint_3
  - name: fake_arm_link_4_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_joint_4
  - name: fake_arm_link_5_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_joint_5
initial:  # Define initial robot poses per group
  - group: arm_link_5
    pose: startup